const voices = [
  { name: 'AIGenerate1Neural', gender: '(Male)', language: 'en-US', types: [] },
  {
    name: 'AIGenerate2Neural',
    gender: '(Female)',
    language: 'en-US',
    types: [],
  },
  { name: 'AmberNeural', gender: '(Female)', language: 'en-US', types: [] },
  { name: 'AnaNeural', gender: '(Female)', language: 'en-US', types: [] },
  {
    name: 'AriaNeural',
    gender: '(Female)',
    language: 'en-US',
    types: [
      'chat',
      'customerservice',
      'narration-professional',
      'newscast-casual',
      'newscast-formal',
      'cheerful',
      'empathetic',
      'angry',
      'sad',
      'excited',
      'friendly',
      'terrified',
      'shouting',
      'unfriendly',
      'whispering',
    ],
  },
  { name: 'AshleyNeural', gender: '(Female)', language: 'en-US', types: [] },
  { name: 'BrandonNeural', gender: '(Male)', language: 'en-US', types: [] },
  { name: 'ChristopherNeural', gender: '(Male)', language: 'en-US', types: [] },
  { name: 'CoraNeural', gender: '(Female)', language: 'en-US', types: [] },
  {
    name: 'DavisNeural',
    gender: '(Male)',
    language: 'en-US',
    types: ['chat', 'angry', 'cheerful', 'excited', 'friendly', 'hopeful', 'sad', 'shouting', 'terrified', 'unfriendly'],
  },
  { name: 'ElizabethNeural', gender: '(Female)', language: 'en-US', types: [] },
  { name: 'EricNeural', gender: '(Male)', language: 'en-US', types: [] },
  {
    name: 'GuyNeural',
    gender: '(Male)',
    language: 'en-US',
    types: ['newscast', 'angry', 'cheerful', 'sad', 'excited', 'friendly', 'terrified', 'shouting', 'unfriendly', 'whispering'],
  },
  { name: 'JacobNeural', gender: '(Male)', language: 'en-US', types: [] },
  {
    name: 'JaneNeural',
    gender: '(Female)',
    language: 'en-US',
    types: ['angry', 'cheerful', 'excited', 'friendly', 'hopeful', 'sad', 'shouting', 'terrified', 'unfriendly'],
  },
  {
    name: 'JasonNeural',
    gender: '(Male)',
    language: 'en-US',
    types: ['angry', 'cheerful', 'excited', 'friendly', 'hopeful', 'sad', 'shouting', 'terrified', 'unfriendly'],
  },
  {
    name: 'JennyMultilingualNeural',
    gender: '(Female)',
    language: 'en-US',
    types: [],
  },
  {
    name: 'JennyNeural',
    gender: '(Female)',
    language: 'en-US',
    types: [
      'assistant',
      'chat',
      'customerservice',
      'newscast',
      'angry',
      'cheerful',
      'sad',
      'excited',
      'friendly',
      'terrified',
      'shouting',
      'unfriendly',
      'whispering',
    ],
  },
  { name: 'MichelleNeural', gender: '(Female)', language: 'en-US', types: [] },
  { name: 'MonicaNeural', gender: '(Female)', language: 'en-US', types: [] },
  {
    name: 'NancyNeural',
    gender: '(Female)',
    language: 'en-US',
    types: ['angry', 'cheerful', 'excited', 'friendly', 'hopeful', 'sad', 'shouting', 'terrified', 'unfriendly'],
  },
  { name: 'RogerNeural', gender: '(Male)', language: 'en-US', types: [] },
  {
    name: 'SaraNeural',
    gender: '(Female)',
    language: 'en-US',
    types: ['angry', 'cheerful', 'excited', 'friendly', 'hopeful', 'sad', 'shouting', 'terrified', 'unfriendly'],
  },
  { name: 'SteffanNeural', gender: '(Male)', language: 'en-US', types: [] },
  {
    name: 'TonyNeural',
    gender: '(Male)',
    language: 'en-US',
    types: ['angry', 'cheerful', 'excited', 'friendly', 'hopeful', 'sad', 'shouting', 'terrified', 'unfriendly'],
  },
]

export default voices
